server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: |-
    &bPlayer&dFarms &6Create your own server!
    &rLet's enjoy!
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 30
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - playerfarms.command.hub
  - playerfarms.command.server
  - playerfarms.command
  admin:
  - bungeetablist.admin
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeeplugins.command
  - antibot.admin-ab
  - antibot.notifications
  - bmycmd.admin
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  Pitan_MAD:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: e2dc56d2-48b5-45c1-a727-3c3e67f33257
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: ''
    address: localhost:25566
    restricted: false
